site_name: Documentation
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
theme:
  favicon: assets/images/favicon.png
  logo: assets/logo.svg
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
      primary: stylesheets/extra.css


